name: Publish Nuget Packages

on: [push, pull_request]

env:
  MSBuildEnableWorkloadResolver: false

jobs:
  deploy:
    runs-on: windows-latest    
    name: Nuget package deployment
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Build and test
      working-directory: ${{github.workspace}}
      run: ./build.ps1 -Configuration Release

    - name: Copy NuGet packages to Artifact staging directory
      run: Copy '/Sharp*/bin/Release/Sharp*@(.nupkg|.snupkg)' '${{ github.workspace }}'

    - name: Publish NuGet Packages
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}
        name: NuGet Packages
